# Generated by Django 2.1.2 on 2019-04-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20190418_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='code',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
