# Generated by Django 2.1.1 on 2018-12-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.PositiveIntegerField(unique=True)),
                ('place', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DataTeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_code', models.PositiveIntegerField(unique=True)),
                ('place', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DEG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Midterm'), ('2', 'Quiz'), ('3', 'Report'), ('4', 'Absence'), ('5', 'Section'), ('6', 'LAB')], max_length=100)),
                ('deg', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm', models.PositiveIntegerField(blank=True)),
                ('final', models.PositiveIntegerField(blank=True)),
                ('total', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('0', 'اعدادي'), ('1', 'مدني'), ('2', 'اتصلات'), ('3', 'عمارة'), ('4', 'مشترك')], max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LABDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True)),
                ('LAB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Degree')),
                ('degr', models.ManyToManyField(to='database.DEG')),
            ],
        ),
        migrations.CreateModel(
            name='LectureDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.PositiveIntegerField(blank=True)),
                ('total', models.PositiveIntegerField(blank=True)),
                ('degr', models.ManyToManyField(to='database.DEG')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('0', 'اعدادي'), ('1', 'مدني'), ('2', 'اتصلات'), ('3', 'عمارة'), ('4', 'مشترك')], max_length=100)),
                ('level', models.CharField(blank=True, choices=[('1', 'المستوي الاول'), ('2', 'المستوي الثاني'), ('3', 'المستوي الثالث'), ('4', 'المستوي الرابع')], max_length=100)),
                ('term', models.CharField(blank=True, choices=[('1', 'الترم الاول'), ('2', 'الترم الصيفي'), ('3', 'الترم الثاني')], max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('sucses', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True)),
                ('degr', models.ManyToManyField(to='database.DEG')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentData_code', models.PositiveIntegerField(unique=True)),
                ('place', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('0', 'اعدادي'), ('1', 'مدني'), ('2', 'اتصلات'), ('3', 'عمارة'), ('4', 'مشترك')], max_length=100)),
                ('level', models.CharField(choices=[('1', 'المستوي الاول'), ('2', 'المستوي الثاني'), ('3', 'المستوي الثالث'), ('4', 'المستوي الرابع')], max_length=100)),
                ('term', models.CharField(choices=[('1', 'الترم الاول'), ('2', 'الترم الصيفي'), ('3', 'الترم الثاني')], max_length=100)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('Specialization', models.CharField(choices=[('1', 'ثقافي'), ('2', 'معهد'), ('3', 'الشعبة'), ('4', 'التخصص')], max_length=100)),
                ('department', models.CharField(choices=[('0', 'اعدادي'), ('1', 'مدني'), ('2', 'اتصلات'), ('3', 'عمارة'), ('4', 'مشترك')], max_length=100)),
                ('no_hours', models.PositiveIntegerField()),
                ('Optional', models.CharField(choices=[('1', 'اجباري'), ('2', 'اختياري')], max_length=100)),
                ('level', models.CharField(choices=[('1', 'المستوي الاول'), ('2', 'المستوي الثاني'), ('3', 'المستوي الثالث'), ('4', 'المستوي الرابع')], max_length=100)),
                ('term', models.CharField(choices=[('1', 'الترم الاول'), ('2', 'الترم الصيفي'), ('3', 'الترم الثاني')], max_length=100)),
                ('Requirement', models.ManyToManyField(blank=True, related_name='_subject_Requirement_+', to='database.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAction', models.CharField(choices=[('lec', 'lecture'), ('sec', 'section'), ('lab', 'lab')], max_length=100)),
                ('interval', models.CharField(choices=[('1', 'الاولي'), ('2', 'الثانية'), ('3', 'الثالثة'), ('4', 'الرابعة')], max_length=100)),
                ('location', models.CharField(max_length=400)),
                ('year', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('1', 'الترم الاول'), ('2', 'الترم الصيفي'), ('3', 'الترم الثاني')], max_length=100)),
                ('day', models.CharField(choices=[('1', 'السبت'), ('2', 'الاحد'), ('3', 'الاثنين'), ('4', 'الثلاثاء'), ('5', 'الاربعاء'), ('6', 'الخميس')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('0', 'اعدادي'), ('1', 'مدني'), ('2', 'اتصلات'), ('3', 'عمارة'), ('4', 'مشترك')], max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='Assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='table',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Doctors'),
        ),
        migrations.AddField(
            model_name='table',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='TeachindAssistanc',
            field=models.ManyToManyField(blank=True, related_name='subject113', to='database.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='subject',
            name='dector',
            field=models.ManyToManyField(related_name='subject112', to='database.Doctors'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lab_Assistanc',
            field=models.ManyToManyField(blank=True, related_name='subject114', to='database.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='students',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Students_user'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Students_user'),
        ),
        migrations.AddField(
            model_name='registersubject',
            name='current_A',
            field=models.ManyToManyField(blank=True, related_name='subject110', to='database.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='registersubject',
            name='current_D',
            field=models.ManyToManyField(blank=True, related_name='subject19', to='database.Doctors'),
        ),
        migrations.AddField(
            model_name='registersubject',
            name='current_L',
            field=models.ManyToManyField(blank=True, related_name='subject111', to='database.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='registersubject',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject00', to='database.Students'),
        ),
        migrations.AddField(
            model_name='registersubject',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject18', to='database.Subject'),
        ),
        migrations.AddField(
            model_name='degree',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student31', to='database.Students'),
        ),
        migrations.AddField(
            model_name='degree',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject12', to='database.RegisterSubject'),
        ),
        migrations.AddField(
            model_name='datateachingassistant',
            name='ta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='datadoctor',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Doctors'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('subject', 'day', 'interval', 'nameAction', 'location', 'year', 'term'), ('day', 'interval', 'year', 'term', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='students_user',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('student', 'department', 'level', 'term', 'year'), ('term', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='registersubject',
            unique_together={('students', 'subjects')},
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('subject', 'student')},
        ),
    ]
