# Generated by Django 2.1.5 on 2019-03-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='gender',
            new_name='gende',
        ),
    ]
