# Generated by Django 2.1.1 on 2018-12-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdegree',
            name='degr',
            field=models.ManyToManyField(blank=True, to='database.DEG'),
        ),
        migrations.AlterField(
            model_name='lecturedegree',
            name='degr',
            field=models.ManyToManyField(blank=True, to='database.DEG'),
        ),
        migrations.AlterField(
            model_name='sectiondegree',
            name='degr',
            field=models.ManyToManyField(blank=True, to='database.DEG'),
        ),
    ]
