# Generated by Django 2.1.2 on 2019-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='department',
            field=models.CharField(blank=True, choices=[('0', 'اعدادي'), ('1', 'مدني'), ('2', 'اتصلات'), ('3', 'عمارة'), ('4', 'مشترك')], max_length=100),
        ),
    ]
