# Generated by Django 2.1.1 on 2018-12-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181214_0022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('student', 'department', 'level', 'term', 'year'), ('student', 'term', 'year')},
        ),
    ]
