# Generated by Django 2.1.5 on 2019-03-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190327_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='gende',
            new_name='gender',
        ),
    ]
