# Generated by Django 2.1 on 2018-12-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181222_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
    ]
