# Generated by Django 2.1.2 on 2019-01-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190121_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturedegree',
            name='finsh',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiondegree',
            name='finsh',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
