# Generated by Django 2.1.5 on 2019-03-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190327_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثي')], max_length=100),
        ),
    ]
