# Generated by Django 2.1.1 on 2018-12-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20181214_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student31', to='database.Students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject12', to='database.RegisterSubject'),
            preserve_default=False,
        ),
    ]
