# Generated by Django 2.1.2 on 2019-01-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190123_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondegree',
            name='full_degree',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
