# Generated by Django 2.1 on 2018-12-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20181221_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.AlterField(
            model_name='students_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.AlterField(
            model_name='teachingassistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
    ]
