# Generated by Django 2.1.5 on 2019-03-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190327_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثي', 'أنثي')], max_length=100),
        ),
    ]
