# Generated by Django 2.1.1 on 2018-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20181215_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deg',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
