# Generated by Django 2.1.1 on 2018-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20181215_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(blank=True)),
                ('deg', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='labdegree',
            name='absence',
            field=models.ManyToManyField(blank=True, to='database.Absence'),
        ),
        migrations.AddField(
            model_name='lecturedegree',
            name='absence',
            field=models.ManyToManyField(blank=True, to='database.Absence'),
        ),
        migrations.AddField(
            model_name='sectiondegree',
            name='absence',
            field=models.ManyToManyField(blank=True, to='database.Absence'),
        ),
    ]
