# Generated by Django 2.1.2 on 2019-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_sectiondegree_full_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labdegree',
            old_name='total',
            new_name='absence_degree',
        ),
        migrations.RemoveField(
            model_name='labdegree',
            name='LAB',
        ),
        migrations.RemoveField(
            model_name='labdegree',
            name='degr',
        ),
        migrations.AddField(
            model_name='labdegree',
            name='absence_total',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiondegree',
            name='absence_degree',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiondegree',
            name='absence_total',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
