# Generated by Django 2.1.5 on 2019-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190327_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
