# Generated by Django 2.1.1 on 2018-12-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20181216_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='deg',
        ),
        migrations.AddField(
            model_name='absence',
            name='check',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
