# Generated by Django 2.1.2 on 2019-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190123_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='deg',
            name='show',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
