# Generated by Django 2.1.2 on 2018-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20181216_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='deg',
            name='full',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
