# Generated by Django 2.1.5 on 2019-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_deg_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='final',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
    ]
