# Generated by Django 2.1.2 on 2018-12-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_deg_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturedegree',
            name='absence_degree',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturedegree',
            name='absence_total',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
